// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace HHFramework.DataTable
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct DTBattleAttrList : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_1_4(); }
  public static DTBattleAttrList GetRootAsDTBattleAttrList(ByteBuffer _bb) { return GetRootAsDTBattleAttrList(_bb, new DTBattleAttrList()); }
  public static DTBattleAttrList GetRootAsDTBattleAttrList(ByteBuffer _bb, DTBattleAttrList obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public DTBattleAttrList __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public HHFramework.DataTable.DTBattleAttr? DTBattleAttrs(int j) { int o = __p.__offset(4); return o != 0 ? (HHFramework.DataTable.DTBattleAttr?)(new HHFramework.DataTable.DTBattleAttr()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int DTBattleAttrsLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<HHFramework.DataTable.DTBattleAttrList> CreateDTBattleAttrList(FlatBufferBuilder builder,
      VectorOffset DTBattleAttrsOffset = default(VectorOffset)) {
    builder.StartTable(1);
    DTBattleAttrList.AddDTBattleAttrs(builder, DTBattleAttrsOffset);
    return DTBattleAttrList.EndDTBattleAttrList(builder);
  }

  public static void StartDTBattleAttrList(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddDTBattleAttrs(FlatBufferBuilder builder, VectorOffset DTBattleAttrsOffset) { builder.AddOffset(0, DTBattleAttrsOffset.Value, 0); }
  public static VectorOffset CreateDTBattleAttrsVector(FlatBufferBuilder builder, Offset<HHFramework.DataTable.DTBattleAttr>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateDTBattleAttrsVectorBlock(FlatBufferBuilder builder, Offset<HHFramework.DataTable.DTBattleAttr>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateDTBattleAttrsVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<HHFramework.DataTable.DTBattleAttr>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateDTBattleAttrsVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<HHFramework.DataTable.DTBattleAttr>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartDTBattleAttrsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<HHFramework.DataTable.DTBattleAttrList> EndDTBattleAttrList(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<HHFramework.DataTable.DTBattleAttrList>(o);
  }
}


}
