// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace HHFramework.DataTable
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct DTJobLevelList : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_1_4(); }
  public static DTJobLevelList GetRootAsDTJobLevelList(ByteBuffer _bb) { return GetRootAsDTJobLevelList(_bb, new DTJobLevelList()); }
  public static DTJobLevelList GetRootAsDTJobLevelList(ByteBuffer _bb, DTJobLevelList obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public DTJobLevelList __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public HHFramework.DataTable.DTJobLevel? DTJobLevels(int j) { int o = __p.__offset(4); return o != 0 ? (HHFramework.DataTable.DTJobLevel?)(new HHFramework.DataTable.DTJobLevel()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int DTJobLevelsLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<HHFramework.DataTable.DTJobLevelList> CreateDTJobLevelList(FlatBufferBuilder builder,
      VectorOffset DTJobLevelsOffset = default(VectorOffset)) {
    builder.StartTable(1);
    DTJobLevelList.AddDTJobLevels(builder, DTJobLevelsOffset);
    return DTJobLevelList.EndDTJobLevelList(builder);
  }

  public static void StartDTJobLevelList(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddDTJobLevels(FlatBufferBuilder builder, VectorOffset DTJobLevelsOffset) { builder.AddOffset(0, DTJobLevelsOffset.Value, 0); }
  public static VectorOffset CreateDTJobLevelsVector(FlatBufferBuilder builder, Offset<HHFramework.DataTable.DTJobLevel>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateDTJobLevelsVectorBlock(FlatBufferBuilder builder, Offset<HHFramework.DataTable.DTJobLevel>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateDTJobLevelsVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<HHFramework.DataTable.DTJobLevel>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateDTJobLevelsVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<HHFramework.DataTable.DTJobLevel>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartDTJobLevelsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<HHFramework.DataTable.DTJobLevelList> EndDTJobLevelList(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<HHFramework.DataTable.DTJobLevelList>(o);
  }
}


}
