// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace HHFramework.DataTable
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct DTMaterialsList : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_1_4(); }
  public static DTMaterialsList GetRootAsDTMaterialsList(ByteBuffer _bb) { return GetRootAsDTMaterialsList(_bb, new DTMaterialsList()); }
  public static DTMaterialsList GetRootAsDTMaterialsList(ByteBuffer _bb, DTMaterialsList obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public DTMaterialsList __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public HHFramework.DataTable.DTMaterials? DTMaterialss(int j) { int o = __p.__offset(4); return o != 0 ? (HHFramework.DataTable.DTMaterials?)(new HHFramework.DataTable.DTMaterials()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int DTMaterialssLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<HHFramework.DataTable.DTMaterialsList> CreateDTMaterialsList(FlatBufferBuilder builder,
      VectorOffset DTMaterialssOffset = default(VectorOffset)) {
    builder.StartTable(1);
    DTMaterialsList.AddDTMaterialss(builder, DTMaterialssOffset);
    return DTMaterialsList.EndDTMaterialsList(builder);
  }

  public static void StartDTMaterialsList(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddDTMaterialss(FlatBufferBuilder builder, VectorOffset DTMaterialssOffset) { builder.AddOffset(0, DTMaterialssOffset.Value, 0); }
  public static VectorOffset CreateDTMaterialssVector(FlatBufferBuilder builder, Offset<HHFramework.DataTable.DTMaterials>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateDTMaterialssVectorBlock(FlatBufferBuilder builder, Offset<HHFramework.DataTable.DTMaterials>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateDTMaterialssVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<HHFramework.DataTable.DTMaterials>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateDTMaterialssVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<HHFramework.DataTable.DTMaterials>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartDTMaterialssVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<HHFramework.DataTable.DTMaterialsList> EndDTMaterialsList(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<HHFramework.DataTable.DTMaterialsList>(o);
  }
}


}
