// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace HHFramework.DataTable
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct DTShopCategoryList : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_1_4(); }
  public static DTShopCategoryList GetRootAsDTShopCategoryList(ByteBuffer _bb) { return GetRootAsDTShopCategoryList(_bb, new DTShopCategoryList()); }
  public static DTShopCategoryList GetRootAsDTShopCategoryList(ByteBuffer _bb, DTShopCategoryList obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public DTShopCategoryList __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public HHFramework.DataTable.DTShopCategory? DTShopCategorys(int j) { int o = __p.__offset(4); return o != 0 ? (HHFramework.DataTable.DTShopCategory?)(new HHFramework.DataTable.DTShopCategory()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int DTShopCategorysLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<HHFramework.DataTable.DTShopCategoryList> CreateDTShopCategoryList(FlatBufferBuilder builder,
      VectorOffset DTShopCategorysOffset = default(VectorOffset)) {
    builder.StartTable(1);
    DTShopCategoryList.AddDTShopCategorys(builder, DTShopCategorysOffset);
    return DTShopCategoryList.EndDTShopCategoryList(builder);
  }

  public static void StartDTShopCategoryList(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddDTShopCategorys(FlatBufferBuilder builder, VectorOffset DTShopCategorysOffset) { builder.AddOffset(0, DTShopCategorysOffset.Value, 0); }
  public static VectorOffset CreateDTShopCategorysVector(FlatBufferBuilder builder, Offset<HHFramework.DataTable.DTShopCategory>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateDTShopCategorysVectorBlock(FlatBufferBuilder builder, Offset<HHFramework.DataTable.DTShopCategory>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateDTShopCategorysVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<HHFramework.DataTable.DTShopCategory>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateDTShopCategorysVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<HHFramework.DataTable.DTShopCategory>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartDTShopCategorysVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<HHFramework.DataTable.DTShopCategoryList> EndDTShopCategoryList(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<HHFramework.DataTable.DTShopCategoryList>(o);
  }
}


}
