// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace HHFramework.DataTable
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct DTSkillList : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_1_4(); }
  public static DTSkillList GetRootAsDTSkillList(ByteBuffer _bb) { return GetRootAsDTSkillList(_bb, new DTSkillList()); }
  public static DTSkillList GetRootAsDTSkillList(ByteBuffer _bb, DTSkillList obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public DTSkillList __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public HHFramework.DataTable.DTSkill? DTSkills(int j) { int o = __p.__offset(4); return o != 0 ? (HHFramework.DataTable.DTSkill?)(new HHFramework.DataTable.DTSkill()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int DTSkillsLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<HHFramework.DataTable.DTSkillList> CreateDTSkillList(FlatBufferBuilder builder,
      VectorOffset DTSkillsOffset = default(VectorOffset)) {
    builder.StartTable(1);
    DTSkillList.AddDTSkills(builder, DTSkillsOffset);
    return DTSkillList.EndDTSkillList(builder);
  }

  public static void StartDTSkillList(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddDTSkills(FlatBufferBuilder builder, VectorOffset DTSkillsOffset) { builder.AddOffset(0, DTSkillsOffset.Value, 0); }
  public static VectorOffset CreateDTSkillsVector(FlatBufferBuilder builder, Offset<HHFramework.DataTable.DTSkill>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateDTSkillsVectorBlock(FlatBufferBuilder builder, Offset<HHFramework.DataTable.DTSkill>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateDTSkillsVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<HHFramework.DataTable.DTSkill>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateDTSkillsVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<HHFramework.DataTable.DTSkill>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartDTSkillsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<HHFramework.DataTable.DTSkillList> EndDTSkillList(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<HHFramework.DataTable.DTSkillList>(o);
  }
}


}
