// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace HHFramework.DataTable
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct Sys_PrefabList : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_1_4(); }
  public static Sys_PrefabList GetRootAsSys_PrefabList(ByteBuffer _bb) { return GetRootAsSys_PrefabList(_bb, new Sys_PrefabList()); }
  public static Sys_PrefabList GetRootAsSys_PrefabList(ByteBuffer _bb, Sys_PrefabList obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Sys_PrefabList __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public HHFramework.DataTable.Sys_Prefab? SysPrefabs(int j) { int o = __p.__offset(4); return o != 0 ? (HHFramework.DataTable.Sys_Prefab?)(new HHFramework.DataTable.Sys_Prefab()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int SysPrefabsLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<HHFramework.DataTable.Sys_PrefabList> CreateSys_PrefabList(FlatBufferBuilder builder,
      VectorOffset Sys_PrefabsOffset = default(VectorOffset)) {
    builder.StartTable(1);
    Sys_PrefabList.AddSysPrefabs(builder, Sys_PrefabsOffset);
    return Sys_PrefabList.EndSys_PrefabList(builder);
  }

  public static void StartSys_PrefabList(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddSysPrefabs(FlatBufferBuilder builder, VectorOffset SysPrefabsOffset) { builder.AddOffset(0, SysPrefabsOffset.Value, 0); }
  public static VectorOffset CreateSysPrefabsVector(FlatBufferBuilder builder, Offset<HHFramework.DataTable.Sys_Prefab>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateSysPrefabsVectorBlock(FlatBufferBuilder builder, Offset<HHFramework.DataTable.Sys_Prefab>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateSysPrefabsVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<HHFramework.DataTable.Sys_Prefab>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateSysPrefabsVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<HHFramework.DataTable.Sys_Prefab>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartSysPrefabsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<HHFramework.DataTable.Sys_PrefabList> EndSys_PrefabList(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<HHFramework.DataTable.Sys_PrefabList>(o);
  }
}


}
