// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace HHFramework.DataTable
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct Sys_LocalizationList : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_1_4(); }
  public static Sys_LocalizationList GetRootAsSys_LocalizationList(ByteBuffer _bb) { return GetRootAsSys_LocalizationList(_bb, new Sys_LocalizationList()); }
  public static Sys_LocalizationList GetRootAsSys_LocalizationList(ByteBuffer _bb, Sys_LocalizationList obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Sys_LocalizationList __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public HHFramework.DataTable.Sys_Localization? SysLocalizations(int j) { int o = __p.__offset(4); return o != 0 ? (HHFramework.DataTable.Sys_Localization?)(new HHFramework.DataTable.Sys_Localization()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int SysLocalizationsLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<HHFramework.DataTable.Sys_LocalizationList> CreateSys_LocalizationList(FlatBufferBuilder builder,
      VectorOffset Sys_LocalizationsOffset = default(VectorOffset)) {
    builder.StartTable(1);
    Sys_LocalizationList.AddSysLocalizations(builder, Sys_LocalizationsOffset);
    return Sys_LocalizationList.EndSys_LocalizationList(builder);
  }

  public static void StartSys_LocalizationList(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddSysLocalizations(FlatBufferBuilder builder, VectorOffset SysLocalizationsOffset) { builder.AddOffset(0, SysLocalizationsOffset.Value, 0); }
  public static VectorOffset CreateSysLocalizationsVector(FlatBufferBuilder builder, Offset<HHFramework.DataTable.Sys_Localization>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateSysLocalizationsVectorBlock(FlatBufferBuilder builder, Offset<HHFramework.DataTable.Sys_Localization>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateSysLocalizationsVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<HHFramework.DataTable.Sys_Localization>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateSysLocalizationsVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<HHFramework.DataTable.Sys_Localization>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartSysLocalizationsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<HHFramework.DataTable.Sys_LocalizationList> EndSys_LocalizationList(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<HHFramework.DataTable.Sys_LocalizationList>(o);
  }
}


}
