// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace HHFramework.DataTable
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct Sys_Localization : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_1_4(); }
  public static Sys_Localization GetRootAsSys_Localization(ByteBuffer _bb) { return GetRootAsSys_Localization(_bb, new Sys_Localization()); }
  public static Sys_Localization GetRootAsSys_Localization(ByteBuffer _bb, Sys_Localization obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Sys_Localization __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Id { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public string Desc { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetDescBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetDescBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetDescArray() { return __p.__vector_as_array<byte>(6); }
  public string Key { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetKeyBytes() { return __p.__vector_as_span<byte>(8, 1); }
#else
  public ArraySegment<byte>? GetKeyBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public byte[] GetKeyArray() { return __p.__vector_as_array<byte>(8); }
  public string CN { get { int o = __p.__offset(10); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetCNBytes() { return __p.__vector_as_span<byte>(10, 1); }
#else
  public ArraySegment<byte>? GetCNBytes() { return __p.__vector_as_arraysegment(10); }
#endif
  public byte[] GetCNArray() { return __p.__vector_as_array<byte>(10); }
  public string EN { get { int o = __p.__offset(12); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetENBytes() { return __p.__vector_as_span<byte>(12, 1); }
#else
  public ArraySegment<byte>? GetENBytes() { return __p.__vector_as_arraysegment(12); }
#endif
  public byte[] GetENArray() { return __p.__vector_as_array<byte>(12); }

  public static Offset<HHFramework.DataTable.Sys_Localization> CreateSys_Localization(FlatBufferBuilder builder,
      int Id = 0,
      StringOffset DescOffset = default(StringOffset),
      StringOffset KeyOffset = default(StringOffset),
      StringOffset CNOffset = default(StringOffset),
      StringOffset ENOffset = default(StringOffset)) {
    builder.StartTable(5);
    Sys_Localization.AddEN(builder, ENOffset);
    Sys_Localization.AddCN(builder, CNOffset);
    Sys_Localization.AddKey(builder, KeyOffset);
    Sys_Localization.AddDesc(builder, DescOffset);
    Sys_Localization.AddId(builder, Id);
    return Sys_Localization.EndSys_Localization(builder);
  }

  public static void StartSys_Localization(FlatBufferBuilder builder) { builder.StartTable(5); }
  public static void AddId(FlatBufferBuilder builder, int Id) { builder.AddInt(0, Id, 0); }
  public static void AddDesc(FlatBufferBuilder builder, StringOffset DescOffset) { builder.AddOffset(1, DescOffset.Value, 0); }
  public static void AddKey(FlatBufferBuilder builder, StringOffset KeyOffset) { builder.AddOffset(2, KeyOffset.Value, 0); }
  public static void AddCN(FlatBufferBuilder builder, StringOffset CNOffset) { builder.AddOffset(3, CNOffset.Value, 0); }
  public static void AddEN(FlatBufferBuilder builder, StringOffset ENOffset) { builder.AddOffset(4, ENOffset.Value, 0); }
  public static Offset<HHFramework.DataTable.Sys_Localization> EndSys_Localization(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<HHFramework.DataTable.Sys_Localization>(o);
  }
}


}
