// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace HHFramework.DataTable
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct TaskList : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_1_4(); }
  public static TaskList GetRootAsTaskList(ByteBuffer _bb) { return GetRootAsTaskList(_bb, new TaskList()); }
  public static TaskList GetRootAsTaskList(ByteBuffer _bb, TaskList obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public TaskList __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public HHFramework.DataTable.Task? Tasks(int j) { int o = __p.__offset(4); return o != 0 ? (HHFramework.DataTable.Task?)(new HHFramework.DataTable.Task()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int TasksLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<HHFramework.DataTable.TaskList> CreateTaskList(FlatBufferBuilder builder,
      VectorOffset TasksOffset = default(VectorOffset)) {
    builder.StartTable(1);
    TaskList.AddTasks(builder, TasksOffset);
    return TaskList.EndTaskList(builder);
  }

  public static void StartTaskList(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddTasks(FlatBufferBuilder builder, VectorOffset TasksOffset) { builder.AddOffset(0, TasksOffset.Value, 0); }
  public static VectorOffset CreateTasksVector(FlatBufferBuilder builder, Offset<HHFramework.DataTable.Task>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateTasksVectorBlock(FlatBufferBuilder builder, Offset<HHFramework.DataTable.Task>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateTasksVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<HHFramework.DataTable.Task>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateTasksVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<HHFramework.DataTable.Task>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartTasksVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<HHFramework.DataTable.TaskList> EndTaskList(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<HHFramework.DataTable.TaskList>(o);
  }
}


}
